### ISSUE TITLE
can use LegacyWrapper to do a bridge so that 32 bit app call 64 bit DLL?

### ISSUE THREAD

**Issue by nadir2102** [CodefoundryDE/LegacyWrapper#24]
Hi
I'm in Windows 10 64 bit

I have a 32bit .exe app that call a 32bit plugin .dll (maybe written in C++?) an all works ok, but for many reasons I would like to use the same version of the .dll already builded in 64bit architecture. So I already have both 32 and 64 bit of the plugin .dll in the exactly same version - I have 2 .dll files (one X86 and one X64). Of coruse my app (32bit) cannot directly use the 64bit one. I wonder if is there a way by using this tool to use the 64bit dll in my 32bit app. In this link I attach the 2 .dll files: one is X86 build, and one is X64 

<-->

Can I do this? thanks a lot

**Comment by zalintyre** [comment]
You already have two versions of the DLL - why don't you just use the 64bit DLL with the 64bit application?

**Comment by nadir2102** [comment]
dear zalintyre, my app is only x86 but - if possible - for various reasons I need to use the 64bit DLL with the 32bit app

this is my dll's:
https://www.dropbox.com/s/ktv86wjrx8wsjz9/BFX.rar?dl=0

**Comment by zalintyre** [comment]
So if your app is a .NET project, you can use LegacyWrapper.
