### ISSUE TITLE
64 in 32!

### ISSUE THREAD

**Issue by rjm2k** [CodefoundryDE/LegacyWrapper#3]
greetings and thanks again for this work, I wonder if you have considered the reverse option, using a 64 bit dll in a 32 bit process?  I will work to amend the code myself but it's nice to have in nuget if you ever get the chance to do it.

thanks

**Comment by zalintyre** [comment]
If you want to create a pull request, I can create a new nuget package out of it.
I think it should be possible to choose the right wrapper exe from code then (default to the 32bit wrapper).

**Comment by zalintyre** [comment]
@rjm2k have you started working on a solution already? I'm asking because I came up with a few ideas how to implement that request and I would work on this myself when I get some spare time.

**Comment by rjm2k** [comment]
Not yet, something else came up.
Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zalintyre** [comment]
Hi @rjm2k, 

please check out LegacyWrapper 2.1 ;) You can now load 64bit DLLs in a 32bit process (if your OS is 64bit).

Greetings,
Franz

**Comment by rjm2k** [comment]
Great thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zalintyre** [comment]
With #4, I consider this issue resolved.
