### ISSUE TITLE
LegacyWrapper freezing when highlighting address.

### ISSUE THREAD

**Issue by aaronb317** [CodefoundryDE/LegacyWrapper#41]
Hi,

I work for an MSP and one of our clients consistently has a problem with their UPS shipping manager freezing when highlighting an address. They use QuickBooks for everything and they print out shipping labels through quickbooks' UPS shipping manager. When it opens they always highlight the company name and delete it. When they highlight the company name however, it freezes the shipping manager window. The shipping manager is run by legacy wrapper. It only ever happens on one of their computers, and it works correctly on all of their other computers. It doesn't freeze every time they use it, and every time I've used remote desktop to recreate the problem it works as it should without freezing. Last time they left the error message up and it said legacy wrapper has stopped working. In task manager "Codefoundry.LegacyWrapper32.exe LegacyWrapper32 (32 bit)" is the exact name for it if that helps. I have tried uninstalling and reinstalling QuickBooks (legacywrapper is part of quickbooks program file) and it is still happening after that. Any help would be appreciated, thanks.

**Comment by zalintyre** [comment]
Hi,

this seems like an implementation detail of the QuickBooks software and not related to LegacyWrapper functionality. Kindly reach out to QuickBooks to get the error resolved.

Greetings
Franz
