### ISSUE TITLE
Is it possible to wrap a DLL belonging to commercial software?

### ISSUE THREAD

**Issue by Mugsy323** [CodefoundryDE/LegacyWrapper#46]
I'd like to "wrap" a 32bit DLL that was written for use with another program (not written by me.)

I know I can include a wrapped DLL to my _own_ VS code, but that's not what I need.

TIA

**Comment by zalintyre** [comment]
Hello @Mugsy323 , to use the LegacyWrapper, you must edit the source code of the application.
